server {
  listen 80;
  listen [::]:80;

  server_name 167.233.152.145;
  root /home/andreas/Projekte/Autohaus-App;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(?:js|css|png|jpg|jpeg|svg|webmanifest|pdf|csv|md)$ {
    try_files $uri =404;
    expires 7d;
    add_header Cache-Control "public";
  }

  location ~ /\. {
    deny all;
  }
}
